### ISSUE TITLE
Neural Mode broken on Mac in v. 1.2.0

### ISSUE THREAD

**Issue by mwdiers** [jatinchowdhury18/KlonCentaur#3]
In the Neural mode, all I get is crackling. Tried the AU, VST, and VST3 in a variety of DAWs. This is on a 2019 16" Macbook Pro i9.

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this! Kind of a weird thing: when I downloaded v1.2.0 and tested on a Mac, I got the same behavior you described, but when I built from the source code at v1.2.0 everything worked okay.

If you wouldn't mind, could you try these builds: https://github.com/jatinchowdhury18/KlonCentaur/blob/master/bin/ChowCentaur-Mac-1.2.0.zip

**Comment by mwdiers** [comment]
That build worked fine.

**Comment by jatinchowdhury18** [comment]
Great! I've updated the link in the downloads page to point to the corrected builds. Thanks again for reporting!
