### ISSUE TITLE
1.2.0: pop/click in Neural mode when loading plugin/project

### ISSUE THREAD

**Issue by pauleye** [jatinchowdhury18/KlonCentaur#6]
If I have the plugin in Neural mode, it makes a pop/click sound when I load a project. This is in REAPER x64 on Windows 10 Pro 20H2 x64. Both the VST2 and VST3 have this behaviour. There's also a pop/click when switching between the modes.
Also, when rendering in REAPER the pop/click gets rendered in the beginning of the file, and this project I'm working on has a guitar track with KlonCentaur send to a delay and reverb (which also the pop/click goes through and overlaps the intro in the rendered file).

**Comment by jatinchowdhury18** [comment]
@pauleye thanks for the detailed bug report, sorry it's taken me a couple days to get to it.

I've put together a fix, and generated some new builds for Windows. If you have a minute, could you download the new build and give it a try in Reaper? The new builds can be downloaded [here](https://github.com/jatinchowdhury18/KlonCentaur/tree/pop-fixes/bin).

**Comment by pauleye** [comment]
Thanks for the reply, and don't worry about a few days delay :)
Unfortunately, this is what I get when loading my project, latest REAPER version (currently 6.21)
![CentaurNA-REAPER](https://user-images.githubusercontent.com/59901371/105623058-59e35580-5e1f-11eb-8307-824e88056234.png)
This is with the VST3 version. I don't have a project with the VST2 version right now, but I can do a test project if needed. The project does reference the correct plugin file name (as of course I replaced the release version with this new build).

What's strange is that I can load the plugin into a new project and it works fine. I can also remove it from, and then re-add it to my project, and it also loads fine. I did have to revert to the release version and save the settings as a preset of course (and the preset does load the correct values in the new build).
So there seems to be an incompatibility between the 2 versions. I don't know if it's REAPER specific, and I don't have any other DAW to test with.

**Comment by jatinchowdhury18** [comment]
Hmm, that is very strange... I wonder if Reaper doesn't like that I'm giving it a different binary with the same version number. I tried making a new build, now with the version 1.2.1. Could you check if that works for you? Downloads are at the [same link](https://github.com/jatinchowdhury18/KlonCentaur/tree/pop-fixes/bin).

Thanks,
Jatin

**Comment by pauleye** [comment]
Unfortunately, that didn't work either. I did save a new version of my project with the previous 1.2.0 test build and that project loads without problems with the 1.2.1 build.
Maybe it's something REAPER specific then. I could post this (and link to this issue if that's OK) on the REAPER forums and see if anyone has an idea what's the problem here?

**Comment by jatinchowdhury18** [comment]
That would be great! Yes, definitely feel free to link to this issue.

Just to double check, is the clicking behaviour better with the new builds?

**Comment by pauleye** [comment]
> Just to double check, is the clicking behaviour better with the new builds?

There still is a faint click that peaks at around -92dB with default settings and Neural mode (compared to around -21dB with the release version) so at least it's not audible anymore. This is in a 1-track test project with no other plugins, track fader at unity. In a mix it'll obviously be lower :)

**Comment by jatinchowdhury18** [comment]
Okay, great! I'll see if I can tweak things a little more, and hopefully eliminate that click altogether :).

**Comment by pauleye** [comment]
Here's my post on the REAPER forum: https://forum.cockos.com/showthread.php?t=248504
Let's hope someone figures out what causes this :)

**Comment by jatinchowdhury18** [comment]
Since the original issue on this thread is fixed, I'm going to go ahead and merge these changes. I'll keep an eye on the Reaper Forum thread, in hopes that someone with some experience can help there!

**Comment by pauleye** [comment]
Thanks.
There doesn't seem to be a new build (yet?). Would be nice to test the fixed version :)
And it seems like the REAPER thread didn't really pick up anyone's attention, unfortunately.

**Comment by jatinchowdhury18** [comment]
Ah, sorry I had forgottento generate new builds. Try these: https://github.com/jatinchowdhury18/KlonCentaur/tree/master/bin

**Comment by pauleye** [comment]
Thanks, the pop/click issue is fixed now :)
Unfortunately the loading issue in REAPER is still there. Maybe I could post on KVR, see if it's just a REAPER issue or if it affects some other DAWs too.
I did save a new version of my project with the newest build, and I'll probably stick to that for the time being.
